# Convenience script with your specific resource names

# Update these values based on your deployment
$subscriptionId = "220fc532-6091-423c-8ba0-66c2397d591b"  # Your subscription ID
$resourceGroupName = "rg-prod-{resourceToken}"  # Will be generated by deployment
$managedIdentityName = "id-vibestory-{resourceToken}"  # Will be generated by deployment
$openAIResourceName = "eastus"  # Your existing OpenAI resource name
$cosmosAccountName = "vibestory-cosmos"  # Your existing Cosmos account name

Write-Host "This script will assign permissions after deployment." -ForegroundColor Yellow
Write-Host "Make sure to update the resource group and managed identity names after running 'azd up'" -ForegroundColor Yellow
Write-Host ""
Write-Host "Example usage after deployment:" -ForegroundColor Green
Write-Host ".\scripts\assign-permissions.ps1 -ManagedIdentityName 'id-vibestory-abc123' -ResourceGroupName 'rg-prod-abc123' -OpenAIResourceName '$openAIResourceName' -CosmosAccountName '$cosmosAccountName' -SubscriptionId '$subscriptionId'" -ForegroundColor Gray
