name: Trigger auto deployment for vibestory-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/vibestory-prod-AutoDeployTrigger-b8754d87-e169-4ae0-bbd0-1d7774d1c3ad.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.VIBESTORYPROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VIBESTORYPROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VIBESTORYPROD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.VIBESTORYPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VIBESTORYPROD_REGISTRY_PASSWORD }}
          containerAppName: vibestory-prod
          resourceGroup: vibestory-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


